// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEG-toX7U46uKlW4o3d1vyTFoJoAHXhXY',
    appId: '1:545296632025:web:321fefa429912bfdde96c8',
    messagingSenderId: '545296632025',
    projectId: 'webrtc-test-23ac4',
    authDomain: 'webrtc-test-23ac4.firebaseapp.com',
    storageBucket: 'webrtc-test-23ac4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBquPJqVXtIkvTVHKd6XS-5P7wdn1l9nXc',
    appId: '1:545296632025:android:fe3062626003f998de96c8',
    messagingSenderId: '545296632025',
    projectId: 'webrtc-test-23ac4',
    storageBucket: 'webrtc-test-23ac4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyJadxMuPF6uK9RNMW-LrjG9vrp0E5R7o',
    appId: '1:545296632025:ios:2184b508d74491fede96c8',
    messagingSenderId: '545296632025',
    projectId: 'webrtc-test-23ac4',
    storageBucket: 'webrtc-test-23ac4.appspot.com',
    iosClientId: '545296632025-14efn0nev06q3h1r7uh5h6uhl98dvc8d.apps.googleusercontent.com',
    iosBundleId: 'com.gariskode.webrtcFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyJadxMuPF6uK9RNMW-LrjG9vrp0E5R7o',
    appId: '1:545296632025:ios:2184b508d74491fede96c8',
    messagingSenderId: '545296632025',
    projectId: 'webrtc-test-23ac4',
    storageBucket: 'webrtc-test-23ac4.appspot.com',
    iosClientId: '545296632025-14efn0nev06q3h1r7uh5h6uhl98dvc8d.apps.googleusercontent.com',
    iosBundleId: 'com.gariskode.webrtcFlutter',
  );
}
